scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9000', 'host.docker.internal:9001', 'host.docker.internal:8000']
        labels:
          application: 'Calculator'