apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob
        spec:
          containers:
            - name: cronjob
              image: spotify/alpine:latest
              imagePullPolicy: Always
              command:
                - curl
              args:
                - http://storage-svc:5000/api/storage/delete
          restartPolicy: Never
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 3