---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: storage-svc
  name: storage-svc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    run: storage-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: storage-svc
  name: storage-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: storage-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: storage-svc
    spec:
      containers:
        - image: knedlicc/agi36:storage
          imagePullPolicy: IfNotPresent
          name: storage-svc
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: storage-env
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: storage-env
                  key: redis_port
          ports:
            - containerPort: 5000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/storage/healthz
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/storage/healthz
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-env
type: Opaque
stringData:
  redis_host: "redis"
  redis_port: '6379'
  redis_password: ''